// _NKDCrimsonDocument_EOArchive_English.java
// Generated by EnterpriseObjects palette at Monday, March 14, 2005 12:52:11 PM America/New_York

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _NKDCrimsonDocument_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector10, _iBHelpConnector11, _iBHelpConnector12, _iBHelpConnector13, _iBHelpConnector14, _iBHelpConnector15, _iBHelpConnector16, _iBHelpConnector17, _iBHelpConnector18, _iBHelpConnector19, _iBHelpConnector2, _iBHelpConnector20, _iBHelpConnector21, _iBHelpConnector22, _iBHelpConnector23, _iBHelpConnector24, _iBHelpConnector25, _iBHelpConnector3, _iBHelpConnector4, _iBHelpConnector5, _iBHelpConnector6, _iBHelpConnector7, _iBHelpConnector8, _iBHelpConnector9;
    NKDCrimsonMovieFrameView _nsCustomView0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1, _eoFrame2;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsColorWell0, _nsColorWell1, _nsProgressIndicator0, _nsSlider0, _nsSlider1, _nsSlider2;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton11, _nsButton12, _nsButton13, _nsButton14, _nsButton15, _nsButton16, _nsButton17, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _nsButton18, _nsButton19, _nsButton20, _nsButton21;
    javax.swing.JPanel _nsView0, _nsView1, _nsView2;

    public _NKDCrimsonDocument_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("###0;-#,##0.00"), "");
        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("###0;-#,##0.00"), "");
        _eoFrame2 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        _nsView2 = (JPanel)_eoFrame2.getContentPane();
        _iBHelpConnector25 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton17 = (javax.swing.JButton)_registered(new javax.swing.JButton("Preview Movie"), "");
        _iBHelpConnector24 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton16 = (javax.swing.JButton)_registered(new javax.swing.JButton("Render Movie"), "");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11112");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11112");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBHelpConnector23 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton15 = (javax.swing.JButton)_registered(new javax.swing.JButton("Preview Frame"), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField221");
        _iBHelpConnector22 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton14 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton3121");
        _iBHelpConnector21 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton13 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton312");
        _iBHelpConnector20 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton311");
        _iBHelpConnector19 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton32");
        _iBHelpConnector18 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31");
        _iBHelpConnector17 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton3");
        _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView1 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "emitterBulbCheckbox")) != null)) {
            _nsButton21 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton21");
        } else {
            _nsButton21 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("\"Emitter Bulb\" effect"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cancelButton")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressText")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "frameSlider")) != null)) {
            _nsSlider2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider2");
        } else {
            _nsSlider2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider2");
        }

        _iBHelpConnector16 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "keyframeCheckbox")) != null)) {
            _nsButton20 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton20");
        } else {
            _nsButton20 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Is Keyframe"), "NSButton411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "frameCountText")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "docView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (NKDCrimsonMovieFrameView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (NKDCrimsonMovieFrameView)_registered(new NKDCrimsonMovieFrameView(), "View");
        }

        _iBHelpConnector15 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startWidthSlider")) != null)) {
            _nsSlider1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider1");
        } else {
            _nsSlider1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider211");
        }

        _iBHelpConnector14 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startWidthTF")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        }

        _iBHelpConnector13 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startRoundedCheckbox")) != null)) {
            _nsButton19 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton19");
        } else {
            _nsButton19 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Rounded"), "NSButton411");
        }

        _iBHelpConnector12 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startNudgeLeft")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31221");
        }

        _iBHelpConnector11 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startNudgeDown")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton3211");
        }

        _iBHelpConnector10 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startNudgeRight")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31111");
        }

        _iBHelpConnector9 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "startNudgeUp")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton331");
        }

        _iBHelpConnector8 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endWidthSlider")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider211");
        }

        _iBHelpConnector7 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endWidthTF")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1121");
        }

        _iBHelpConnector6 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endRoundedCheckbox")) != null)) {
            _nsButton18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton18");
        } else {
            _nsButton18 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Rounded"), "NSButton41");
        }

        _iBHelpConnector5 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endNudgeLeft")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31221");
        }

        _iBHelpConnector4 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endNudgeDown")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton3211");
        }

        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endNudgeRight")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31111");
        }

        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "endNudgeUp")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton331");
        }

        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "coreColorWell")) != null)) {
            _nsColorWell1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell1");
        } else {
            _nsColorWell1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211");
        }

        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "auraColorWell")) != null)) {
            _nsColorWell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell0");
        } else {
            _nsColorWell0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressIndicator")) != null)) {
            _nsProgressIndicator0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsProgressIndicator0");
        } else {
            _nsProgressIndicator0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressPanel")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "progress");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "renderMovie", _nsButton17), ""));
        _nsButton16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "renderMovie", _nsButton16), ""));
        _nsButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "previewFrame", _nsButton15), ""));
        _nsButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nextKeyframe", _nsButton14), ""));
        _nsButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "previousKeyframe", _nsButton13), ""));
        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "stepForward", _nsButton12), ""));
        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "stepToEnd", _nsButton11), ""));
        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "stepBack", _nsButton10), ""));
        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "stepToBeginning", _nsButton9), ""));
        _connect(_eoFrame1, _owner(), "delegate");
        _nsButton21.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsButton21), ""));

        if (_replacedObjects.objectForKey("_nsButton21") == null) {
            _connect(_owner(), _nsButton21, "emitterBulbCheckbox");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "cancelButtonPresed", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "cancelButton");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "progressText");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "progressPanel");
        }

        _nsSlider2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changeFrameBasedOnSlider", _nsSlider2), ""));

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _connect(_owner(), _nsSlider2, "frameSlider");
        }

        _nsButton20.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "toggleKeyFrameStatus", _nsButton20), ""));

        if (_replacedObjects.objectForKey("_nsButton20") == null) {
            _connect(_owner(), _nsButton20, "keyframeCheckbox");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "frameCountText");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "docView");
        }

        _nsSlider1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsSlider1), ""));

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _connect(_owner(), _nsSlider1, "startWidthSlider");
        }

        _nsTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsTextField1), ""));

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "startWidthTF");
        }

        _nsButton19.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsButton19), ""));

        if (_replacedObjects.objectForKey("_nsButton19") == null) {
            _connect(_owner(), _nsButton19, "startRoundedCheckbox");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeStart", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "startNudgeLeft");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeStart", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "startNudgeDown");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeStart", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "startNudgeRight");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeStart", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "startNudgeUp");
        }

        _nsSlider0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsSlider0), ""));

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "endWidthSlider");
        }

        _nsTextField0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsTextField0), ""));

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "endWidthTF");
        }

        _nsButton18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsButton18), ""));

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _connect(_owner(), _nsButton18, "endRoundedCheckbox");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeFinish", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "endNudgeLeft");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeFinish", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "endNudgeDown");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeFinish", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "endNudgeRight");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nudgeFinish", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "endNudgeUp");
        }

        _nsColorWell1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsColorWell1), ""));

        if (_replacedObjects.objectForKey("_nsColorWell1") == null) {
            _connect(_owner(), _nsColorWell1, "coreColorWell");
        }

        _nsColorWell0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "takeKeyFrameValuesfrom", _nsColorWell0), ""));

        if (_replacedObjects.objectForKey("_nsColorWell0") == null) {
            _connect(_owner(), _nsColorWell0, "auraColorWell");
        }

        if (_replacedObjects.objectForKey("_nsProgressIndicator0") == null) {
            _connect(_owner(), _nsProgressIndicator0, "progressIndicator");
        }
    }

    protected void _init() {
        super._init();
        _nsNumberFormatter1.setMinimum(new java.math.BigDecimal("1"));
        _nsNumberFormatter1.setMaximum(new java.math.BigDecimal("200"));
        _nsNumberFormatter0.setMinimum(new java.math.BigDecimal("1"));
        _nsNumberFormatter0.setMaximum(new java.math.BigDecimal("200"));
        _nsView2.setSize(346, 228);
        _eoFrame2.setTitle("Panel");
        _eoFrame2.setLocation(403, 270);
        _eoFrame2.setSize(346, 228);
        _setFontForComponent(_nsButton17, "Lucida Grande", 9, Font.PLAIN);
        _nsButton17.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton16, "Lucida Grande", 9, Font.PLAIN);
        _nsButton16.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Nudge:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Width:");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(12, 19);
        _nsButton0.setLocation(48, 4);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton0);
        _nsButton3.setSize(12, 20);
        _nsButton3.setLocation(37, 18);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton3);
        _nsButton1.setSize(12, 20);
        _nsButton1.setLocation(58, 18);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton1);
        _nsButton2.setSize(12, 20);
        _nsButton2.setLocation(48, 32);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton2);
        _nsSlider0.setSize(157, 15);
        _nsSlider0.setLocation(78, 28);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsSlider0);
        _nsTextField0.setSize(28, 19);
        _nsTextField0.setLocation(113, 4);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField0);
        _nsTextField9.setSize(38, 14);
        _nsTextField9.setLocation(76, 7);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField9);
        _nsTextField10.setSize(39, 14);
        _nsTextField10.setLocation(5, 5);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField10);
        _nsButton18.setSize(79, 17);
        _nsButton18.setLocation(145, 6);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsButton18, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsButton18);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(240, 60);
        _nsBox5.setLocation(3, 15);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("End Point", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Core:");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Aura");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Nudge:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Width:");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsButton4.setSize(12, 19);
        _nsButton4.setLocation(48, 4);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton4);
        _nsButton7.setSize(12, 20);
        _nsButton7.setLocation(37, 18);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton7);
        _nsButton5.setSize(12, 20);
        _nsButton5.setLocation(58, 18);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton5);
        _nsButton6.setSize(12, 20);
        _nsButton6.setLocation(48, 32);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton6);
        _nsSlider1.setSize(157, 15);
        _nsSlider1.setLocation(78, 28);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsSlider1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsSlider1);
        _nsTextField1.setSize(28, 19);
        _nsTextField1.setLocation(113, 4);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField1);
        _nsTextField5.setSize(38, 14);
        _nsTextField5.setLocation(76, 7);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField5);
        _nsTextField6.setSize(39, 14);
        _nsTextField6.setLocation(5, 5);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField6);
        _nsButton19.setSize(79, 17);
        _nsButton19.setLocation(145, 6);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton19, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton19);
        _nsButton21.setSize(129, 17);
        _nsButton21.setLocation(95, 40);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton21, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton21);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(240, 60);
        _nsBox3.setLocation(3, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Start Point", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsBox2.setSize(246, 78);
        _nsBox2.setLocation(11, 43);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox2);
        _nsColorWell0.setSize(26, 26);
        _nsColorWell0.setLocation(91, 13);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsColorWell0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsColorWell0);
        _nsTextField7.setSize(34, 14);
        _nsTextField7.setLocation(53, 19);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField7);
        _nsColorWell1.setSize(26, 26);
        _nsColorWell1.setLocation(160, 13);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsColorWell1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsColorWell1);
        _nsTextField8.setSize(33, 14);
        _nsTextField8.setLocation(123, 19);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField8);
        _nsBox4.setSize(246, 78);
        _nsBox4.setLocation(11, 119);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsBox4);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(268, 207);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsButton15, "Lucida Grande", 9, Font.PLAIN);
        _nsButton15.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField4, "SimSun", 46, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("CRIMSON");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsButton14, "Lucida Grande", 10, Font.PLAIN);
        _nsButton14.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton13, "Lucida Grande", 10, Font.PLAIN);
        _nsButton13.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton12, "Lucida Grande", 10, Font.PLAIN);
        _nsButton12.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton11, "Lucida Grande", 10, Font.PLAIN);
        _nsButton11.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton10, "Lucida Grande", 10, Font.PLAIN);
        _nsButton10.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton9, "Lucida Grande", 10, Font.PLAIN);
        _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(720, 480);
        _nsCustomView0.setLocation(13, 14);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsCustomView0);
        _nsButton9.setSize(31, 26);
        _nsButton9.setLocation(11, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton9);
        _nsButton10.setSize(26, 26);
        _nsButton10.setLocation(64, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton10);
        _nsButton11.setSize(31, 26);
        _nsButton11.setLocation(704, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton11);
        _nsButton12.setSize(26, 26);
        _nsButton12.setLocation(654, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton12);
        _nsSlider2.setSize(552, 15);
        _nsSlider2.setLocation(96, 504);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsSlider2, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView1.add(_nsSlider2);
        _nsTextField2.setSize(606, 11);
        _nsTextField2.setLocation(71, 494);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField2);
        _nsButton13.setSize(28, 26);
        _nsButton13.setLocation(39, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton13, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton13);
        _nsButton14.setSize(28, 26);
        _nsButton14.setLocation(679, 498);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton14, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton14);
        _nsTextField4.setSize(173, 50);
        _nsTextField4.setLocation(742, -10);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsTextField4);
        _nsButton15.setSize(87, 16);
        _nsButton15.setLocation(745, 278);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton15, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton15);
        _nsBox0.setSize(272, 211);
        _nsBox0.setLocation(738, 63);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsBox0);
        _nsButton20.setSize(96, 17);
        _nsButton20.setLocation(746, 47);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton20, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton20);
        _nsButton16.setSize(77, 16);
        _nsButton16.setLocation(929, 278);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton16, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton16);
        _nsButton17.setSize(80, 16);
        _nsButton17.setLocation(841, 278);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton17, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView1.add(_nsButton17);
        _nsView1.setSize(1023, 534);
        _eoFrame1.setTitle("Crimson");
        _eoFrame1.setLocation(29, 309);
        _eoFrame1.setSize(1023, 534);

        if (_replacedObjects.objectForKey("_nsButton21") == null) {
            _setFontForComponent(_nsButton21, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
            _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 10, Font.PLAIN);
            _nsTextField3.setEditable(false);
            _nsTextField3.setOpaque(false);
            _nsTextField3.setText("Label Font Text");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField3.setSelectable(false);
            _nsTextField3.setEnabled(true);
            _nsTextField3.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsSlider2") == null) {
            _setFontForComponent(_nsSlider2, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton20") == null) {
            _setFontForComponent(_nsButton20, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 9, Font.PLAIN);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField2.setSelectable(false);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsSlider1") == null) {
            _setFontForComponent(_nsSlider1, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("10");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton19") == null) {
            _setFontForComponent(_nsButton19, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 10, Font.PLAIN);
            _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 10, Font.PLAIN);
            _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 10, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 10, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("10");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _setFontForComponent(_nsButton18, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 10, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 10, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 10, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsProgressIndicator0.setSize(560, 20);
        _nsProgressIndicator0.setLocation(11, 30);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsProgressIndicator0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsProgressIndicator0);
        _nsTextField3.setSize(562, 13);
        _nsTextField3.setLocation(11, 54);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsButton8.setSize(75, 26);
        _nsButton8.setLocation(500, 59);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton8);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(582, 95);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(52, 741);
            _eoFrame0.setSize(582, 95);
        }
    }
}
